### ISSUE TITLE
how to use gerrit-checklist in gerrit 2.11

### ISSUE THREAD

**Issue by wklxd** [mziwisky/gerrit-checklist#5]
hello：
    when i install gerrit-checklist in gerrit 2.11, i got this error

        ReferenceError: $ is not defined
            var gerTextArea = $('.popupContent .gwt-TextArea');

    so i guess gerrit-checklist use jquery。
    but i don't know how to install jquery in gerrit, so can you tell me?

many thanks

**Comment by mziwisky** [comment]
hi, when you say you're "installing" it in gerrit, what exactly do you mean?  I wrote this just as a user script, to be included in the page via a tool like TamperMonkey.  i don't know anything about gerrit administration, but if you're trying to import it as a gerrit plugin or something like that, it probably won't work.

that said, if you're just trying to use it as a userscript and you're getting that error, then the quick and dirty solution would be to just copy and paste the jquery source before this script.  or if you're looking for something more elegant/clever/tricky, you could load jquery dynamically as described here: http://stackoverflow.com/a/950146/2093416

**Comment by wklxd** [comment]
yeah， i got that error when i try to use it as a gerrit plugin。

so, i think i need to try TamperMonkey

many thanks
